name: 'Unit Test'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      -name: Install dependecies
       run: sudo apt-get update && sudo apt-get install cmake -y
      -name: Get repository code
       uses: actions/checkout@v3
        with:
          submodules: true
      -name: Clone gtest library
       run: git clone https://github.com/google/googletest.git
      -name: Build project
       run: cmake --build . --config Release
      -name: Test project
       run: ctest
